name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      # Check out the code
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set NODE_OPTIONS for legacy OpenSSL (if applicable)
      - name: Set NODE_OPTIONS for legacy OpenSSL (if applicable)
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      # Deploy the Gradio app
      - name: Deploy Gradio app
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: "1f56e4424a4b0eab9e734391e8987ec68ced676e1e4b3d719f168864fa86afcc06-2b094e17-091b-4817-8ec4-1198e51d5e1401e03020e88a0b1e"  # Directly pass the API token here
          action: "upload"
          app_location: "/"   # Point to the root directory of the Python project
          api_location: ""    # Leave blank if no API (Gradio app is API-free)
          output_location: "" # Leave empty since Gradio doesn't output static files
          github_id_token: ${{ steps.idtoken.outputs.result }}
        env:
          NODE_OPTIONS: --openssl-legacy-provider

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
